import {
  DIRECTORY_OWNER,
  DISPLAY_USER_BANNER,
  DISPLAY_USER_DESCRIPTION,
  HIDE_OWNER_CARD,
  PUBLIC_LINKAT_USERS,
  PUBLIC_ORIGIN,
} from "$env/static/public";

export const env = {
  DIRECTORY_OWNER,
  DISPLAY_USER_BANNER,
  DISPLAY_USER_DESCRIPTION,
  HIDE_OWNER_CARD,
  PUBLIC_LINKAT_USERS,
  PUBLIC_ORIGIN,
};
